import 'dotenv/config'
export const env = {
  MONGODB_URL: process.env.MONGODB_URL,
  DATABASE_NAME: process.env.DATABASE_NAME,
  HOSTNAME: process.env.HOSTNAME,
  BUILD_MODE: process.env.BUILD_MODE,
  PORT: process.env.PORT,
  DOMAIN_DEV: process.env.DOMAIN_DEV,
  DOMAIN_PRO: process.env.DOMAIN_PRO,
  RESEND_APIKEY: process.env.RESEND_APIKEY,
  ADMIN_EMAIL_ADDRESS: process.env.ADMIN_EMAIL_ADDRESS,
  ADMIN_EMAIL_NAME: process.env.ADMIN_EMAIL_NAME,
  ACCESS_SECRET_SIGNATURE: process.env.ACCESS_SECRET_SIGNATURE,
  ACCESS_TOKEN_LIFE: process.env.ACCESS_TOKEN_LIFE,
  REFRESH_SECRET_SIGNATURE: process.env.REFRESH_SECRET_SIGNATURE,
  REFRESH_TOKEN_LIFE: process.env.REFRESH_TOKEN_LIFE
}